import type { Discipline } from '../types/discipline';

export const MOCK_DISCIPLINES_LIST: Discipline[] = [
  {
    id: 'd1',
    name: 'Математический анализ',
    forType: 'group',
    forIds: ['ri-230001', 'ri-230002'],
    teachers: [{ id: 't1', name: 'Иванов И.И.' }],
    audiences: [{ roomId: '', roomName: 'Тургенева, 301' }],
    isStatic: true,
    canOverlap: false,
    repeat: 'every-week',
    occurrences: [
      { dayId: 'mon', timeStart: '09:00', timeEnd: '10:30' },
      { dayId: 'wed', timeStart: '09:00', timeEnd: '10:30' },
    ],
    dateRange: { from: '01.09.2025', to: '31.12.2025' },
    weeklyCount: 2,
  },
  {
    id: 'd2',
    name: 'Физика',
    forType: 'group',
    forIds: ['ri-230001'],
    teachers: [
      { id: 't2', name: 'Петров П.П.' },
      { id: 't3', name: 'Новикова Е.Н.' },
    ],
    audiences: [
      { roomId: '', roomName: 'Куйбышева, 205' },
      { roomId: '', roomName: 'Куйбышева, 206' },
    ],
    isStatic: false,
    canOverlap: false,
    repeat: 'every-week',
    occurrences: [],
    comment: 'Лекционный курс. Требуется проектор.',
    weeklyCount: 1,
  },
  {
    id: 'd3',
    name: 'Программирование',
    forType: 'group',
    forIds: ['ri-230001', 'ri-230002'],
    teachers: [{ id: 't4', name: 'Сидоров С.С.' }],
    audiences: [],
    isStatic: false,
    canOverlap: true,
    repeat: 'every-week',
    occurrences: [],
    weeklyCount: 1,
  },
  {
    id: 'd4',
    name: 'Английский язык',
    forType: 'group',
    forIds: ['ri-230001-1', 'ri-230001-2'],
    teachers: [{ id: 't5', name: 'Смирнова А.А.' }],
    audiences: [{ roomId: '', roomName: 'Тургенева, 410' }],
    isStatic: true,
    canOverlap: false,
    repeat: 'odd-weeks',
    occurrences: [{ dayId: 'fri', timeStart: '14:30', timeEnd: '16:00' }],
    dateRange: { from: '01.09.2025', to: '31.05.2026' },
    weeklyCount: 1,
  },
  {
    id: 'd5',
    name: 'История',
    forType: 'stream',
    forIds: ['stream-1'],
    teachers: [{ id: 't6', name: 'Козлов В.В.' }],
    audiences: [{ roomId: '', roomName: 'Куйбышева, 101' }],
    isStatic: true,
    canOverlap: false,
    repeat: 'every-week',
    occurrences: [{ dayId: 'tue', timeStart: '10:40', timeEnd: '12:10' }],
    dateRange: { from: '01.09.2025', to: '31.12.2025' },
    weeklyCount: 1,
  },
  {
    id: 'd6',
    name: 'Физкультура',
    forType: 'stream',
    forIds: ['stream-1', 'stream-2'],
    teachers: [{ id: 't7', name: 'Орлов Д.В.' }],
    audiences: [{ roomId: '', roomName: 'Спортивный корпус — Спортзал' }],
    isStatic: false,
    canOverlap: true,
    repeat: 'every-week',
    occurrences: [],
    comment: 'Проводится совместно для нескольких потоков.',
    weeklyCount: 1,
  },
];
