import type { Discipline } from '../types';

export const MOCK_DISCIPLINES: Discipline[] = [
  {
    id: '1',
    name: 'Математический анализ',
    teacher: 'Иванов И.И.',
    building: 'turgeneva',
    audience: '301',
    repeat: 'every-week',
    weeklyCount: 2,
    isStatic: true,
    isInGrid: true,
    dayId: 'mon',
    timeStart: '09:00',
    timeEnd: '10:30',
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  // Дочерняя карточка математики (второй день)
  {
    id: '1-child-wed',
    name: 'Математический анализ',
    teacher: 'Иванов И.И.',
    building: 'turgeneva',
    audience: '301',
    repeat: 'every-week',
    weeklyCount: 1,
    isStatic: true,
    isInGrid: true,
    parentId: '1',
    dayId: 'wed',
    timeStart: '09:00',
    timeEnd: '10:30',
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  {
    id: '2',
    name: 'Физика',
    teacher: 'Петров П.П.',
    building: 'kuybysheva',
    audience: '205',
    repeat: 'every-week',
    weeklyCount: 1,
    isStatic: false,
    isInGrid: true,
    dayId: 'tue',
    timeStart: '10:40',
    timeEnd: '12:10',
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  {
    id: '3',
    name: 'Программирование',
    teacher: 'Сидоров С.С.',
    building: 'online',
    repeat: 'every-week',
    weeklyCount: 1,
    isStatic: false,
    isInGrid: true,
    dayId: 'wed',
    timeStart: '13:00',
    timeEnd: '14:30',
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  {
    id: '4',
    name: 'Английский язык',
    teacher: 'Смирнова А.А.',
    building: 'turgeneva',
    audience: '410',
    repeat: 'even-weeks',
    weeklyCount: 1,
    isStatic: true,
    isInGrid: true,
    dayId: 'fri',
    timeStart: '14:30',
    timeEnd: '16:00',
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  {
    id: '5',
    name: 'История',
    teacher: 'Козлов В.В.',
    building: 'kuybysheva',
    audience: '101',
    repeat: 'every-week',
    weeklyCount: 1,
    isStatic: true,
    isInGrid: false,
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
    canOverlap: false,
  },
  {
    id: '6',
    name: 'Физкультура',
    teacher: 'Орлов Д.В.',
    building: 'turgeneva',
    audience: 'Спортзал',
    repeat: 'every-week',
    weeklyCount: 2,
    isStatic: false,
    isInGrid: true,
    dayId: 'mon',
    timeStart: '09:00',
    timeEnd: '10:30',
    canOverlap: true,
    forIds: ['1', '2'],
    forType: 'group',
    teachers: [],
    audiences: [],
  },
];
